### ISSUE TITLE
test_directive_repr fails on Python 3

### ISSUE THREAD

**Issue by taschini** [morepath/dectate#29]
In `test_directive.py`, the value of `repr(MyApp.foo)` is:

```
<bound method DirectiveDirective.__call__.<locals>.method of 
<class 'dectate.tests.test_directive.test_directive_repr.<locals>.MyApp'>
```

**Comment by faassen** [comment]
We need to get the CI tooling in here and in Reg. @href and @henri-hulski, want to help?

**Comment by faassen** [comment]
Heh, I fixed it for Python 3.4 but now the pypy3 test fails... Ugh.

**Comment by href** [comment]
I'll add a tox.ini to both Reg and Dectate today.

**Comment by faassen** [comment]
Thank you!

**Comment by faassen** [comment]
Anyway, I fixed this test now, though it's a bit wobbly on PyPy 3 as it's possible a newer version of PyPy 3 than I have on my platform produces the same output as Python 3.4 (right now it's the same as Python 2).

**Comment by taschini** [comment]
Unfortunately it still fails with Python 3.5 (See travis report on #32).

**Comment by taschini** [comment]
The reason is that Python 3.5 uses `__qualname__` for the repr of BoundMethod objects: http://bugs.python.org/issue21389#msg217566

**Comment by faassen** [comment]
Thanks for digging that up! Whatever else we do to fix this, I think we need to put a link to this in the code.

**Comment by taschini** [comment]
This should now be in working order.
